# Generated by Django 5.2 on 2025-04-17 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_user_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_brand', models.CharField(choices=[('Reebok', 'Reebok'), ('Adidas', 'Adidas'), ('Nike', 'Nike'), ('Puma', 'Puma')], max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.PositiveIntegerField()),
                ('product_desc', models.TextField()),
                ('product_picture', models.ImageField(upload_to='product_picture/')),
                ('product_category', models.CharField(choices=[('Formal', 'Formal'), ('Sports', 'Sports'), ('Sneaker', 'Sneaker'), ('Party', 'Party')], max_length=100)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
